wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.11
    cli_version: 0.16.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1764159723.604078
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 13
      - 19
      - 23
      4: 3.9.11
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
look_back:
  desc: null
  value: 8
epochs:
  desc: null
  value: 15
batch_size:
  desc: null
  value: 2048
embedding_dim:
  desc: null
  value: 64
large_error_threshold:
  desc: null
  value: 1.5
