_wandb:
    value:
        cli_version: 0.23.0
        e:
            6zwqiqyc6koyjb5sygyzod1ob58p9b1m:
                codePath: train_transformer.py
                codePathLocal: train_transformer.py
                executable: D:\Python\Python312\python.exe
                git:
                    commit: db27c4eb9b4ac0e4e4b3c3346537d8ac47c4cb01
                    remote: https://github.com/AlanMC123/Wd-Pred.git
                host: KanchoTX5Pro
                os: Windows-11-10.0.26100-SP0
                program: f:\Codes\Wd-Pred\train_transformer.py
                python: CPython 3.12.9
                root: F:\Codes\Wd-Pred
                startedAt: "2025-12-07T07:10:40.176245Z"
                writerId: 6zwqiqyc6koyjb5sygyzod1ob58p9b1m
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.12.9
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
batch_size:
    value: 1024
dropout_rate:
    value: 0.45
embedding_dim:
    value: 16
epochs:
    value: 30
ff_dim:
    value: 16
guess_feat_len:
    value: 8
guess_sequence_len:
    value: 6
learning_rate:
    value: 0.0002
look_back:
    value: 5
model_type:
    value: Transformer (Complex Reg)
num_heads:
    value: 6
project_dim:
    value: 16
seed:
    value: 42
transformer_layers:
    value: 1
