_wandb:
    value:
        cli_version: 0.23.0
        e:
            19kipz82txo2ugf583l6rl3qsgvbl87j:
                codePath: train_transformer.py
                codePathLocal: train_transformer.py
                executable: D:\Python\Python312\python.exe
                git:
                    commit: 80002c8d3f6a90f377d90b9f5b52f11ddc9feab0
                    remote: https://github.com/AlanMC123/Wd-Pred.git
                host: KanchoTX5Pro
                os: Windows-11-10.0.26100-SP0
                program: f:\Codes\Wd-Pred\train_transformer.py
                python: CPython 3.12.9
                root: F:\Codes\Wd-Pred
                startedAt: "2025-12-07T14:45:46.718643Z"
                writerId: 19kipz82txo2ugf583l6rl3qsgvbl87j
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
            "3":
                - 2
                - 13
                - 61
            "4": 3.12.9
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
