wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.11
    cli_version: 0.16.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1764471923.796797
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 13
      - 19
      - 23
      4: 3.9.11
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
look_back:
  desc: null
  value: 8
epochs:
  desc: null
  value: 15
batch_size:
  desc: null
  value: 4096
embedding_dim:
  desc: null
  value: 64
num_heads:
  desc: null
  value: 8
ff_dim:
  desc: null
  value: 256
transformer_layers:
  desc: null
  value: 4
dropout_rate:
  desc: null
  value: 0.3
learning_rate:
  desc: null
  value: 0.0005
patience:
  desc: null
  value: 4
large_error_threshold:
  desc: null
  value: 1.5
