_wandb:
    value:
        cli_version: 0.23.0
        e:
            8hiol3s40mi2bbrn8n5fb2qez7a4v0iy:
                codePath: train_transformer.py
                codePathLocal: train_transformer.py
                executable: D:\Python\Python312\python.exe
                git:
                    commit: db27c4eb9b4ac0e4e4b3c3346537d8ac47c4cb01
                    remote: https://github.com/AlanMC123/Wd-Pred.git
                host: KanchoTX5Pro
                os: Windows-11-10.0.26100-SP0
                program: f:\Codes\Wd-Pred\train_transformer.py
                python: CPython 3.12.9
                root: F:\Codes\Wd-Pred
                startedAt: "2025-12-07T07:20:53.616424Z"
                writerId: 8hiol3s40mi2bbrn8n5fb2qez7a4v0iy
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.12.9
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
L2_REG:
    value: 0.005
dropout:
    value: 0.45
epochs:
    value: 40
learning_rate:
    value: 0.0001
model_type:
    value: Transformer (Regularized)
