_wandb:
    value:
        cli_version: 0.23.0
        e:
            ru3i0w7x6jehc4c8pf4n9qp3vvxht8i4:
                codePath: LSTM_prediction.py
                codePathLocal: LSTM_prediction.py
                executable: D:\Python\Python312\python.exe
                git:
                    commit: b811a3297330e26d5ffada8c3bc281c401322550
                    remote: https://github.com/AlanMC123/Wd-Pred.git
                host: KanchoTX5Pro
                os: Windows-11-10.0.26100-SP0
                program: f:\Codes\Wd-Pred\LSTM_prediction.py
                python: CPython 3.12.9
                root: F:\Codes\Wd-Pred
                startedAt: "2025-12-01T15:26:42.788049Z"
                writerId: ru3i0w7x6jehc4c8pf4n9qp3vvxht8i4
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.12.9
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
batch_size:
    value: 1024
dropout_rate:
    value: 0.4
embedding_dim:
    value: 24
epochs:
    value: 20
grid_seq_feat_dim:
    value: 4
learning_rate:
    value: 0.0005
look_back:
    value: 5
lstm_units:
    value: 48
model_type:
    value: LSTM_Grid_Seq_Simplified
seed:
    value: 42
