_wandb:
    value:
        cli_version: 0.23.0
        e:
            6xeslx1iipwo9d1r0z7bqb94zc8mzyjb:
                codePath: train_LSTM.py
                codePathLocal: train_LSTM.py
                executable: D:\Python\Python312\python.exe
                git:
                    commit: db27c4eb9b4ac0e4e4b3c3346537d8ac47c4cb01
                    remote: https://github.com/AlanMC123/Wd-Pred.git
                host: KanchoTX5Pro
                os: Windows-11-10.0.26100-SP0
                program: f:\Codes\Wd-Pred\train_LSTM.py
                python: CPython 3.12.9
                root: F:\Codes\Wd-Pred
                startedAt: "2025-12-07T08:18:02.965399Z"
                writerId: 6xeslx1iipwo9d1r0z7bqb94zc8mzyjb
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.12.9
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
GRID_FEAT_LEN:
    value: 8
batch_size:
    value: 1024
dropout_rate:
    value: 0.45
embedding_dim:
    value: 24
epochs:
    value: 40
learning_rate:
    value: 0.0005
look_back:
    value: 5
lstm_units:
    value: 56
model_type:
    value: LSTM_Complex_Reg
seed:
    value: 42
