_wandb:
    value:
        cli_version: 0.23.0
        e:
            6q1vlecli11txf4amar2pozarnm8qron:
                codePath: transformer_prediction.py
                codePathLocal: transformer_prediction.py
                executable: D:\Python\Python312\python.exe
                git:
                    commit: d64c6db3930d31c12912565942c35d5909a97c58
                    remote: https://github.com/AlanMC123/Wd-Pred.git
                host: KanchoTX5Pro
                os: Windows-11-10.0.26100-SP0
                program: f:\Codes\Wd-Pred\transformer_prediction.py
                python: CPython 3.12.9
                root: F:\Codes\Wd-Pred
                startedAt: "2025-12-02T08:03:36.550543Z"
                writerId: 6q1vlecli11txf4amar2pozarnm8qron
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.12.9
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
batch_size:
    value: 1024
dropout_rate:
    value: 0.45
embedding_dim:
    value: 16
epochs:
    value: 20
ff_dim:
    value: 16
guess_feat_len:
    value: 8
guess_sequence_len:
    value: 6
learning_rate:
    value: 0.0002
look_back:
    value: 5
model_type:
    value: Transformer (Guess Seq) - fixed
num_heads:
    value: 6
project_dim:
    value: 16
seed:
    value: 42
transformer_layers:
    value: 1
