wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.11
    cli_version: 0.16.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1764411454.772373
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.9.11
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
