_wandb:
    value:
        cli_version: 0.23.0
        e:
            d7w1u5mprpwp4jfckf47ou0vahbjtwhe:
                codePath: train_LSTM.py
                codePathLocal: train_LSTM.py
                executable: D:\Python\Python312\python.exe
                git:
                    commit: 65d6cefea9c12cb7039f79245e506a3f9399ebba
                    remote: https://github.com/AlanMC123/Wd-Pred.git
                host: KanchoTX5Pro
                os: Windows-11-10.0.26100-SP0
                program: f:\Codes\Wd-Pred\train_LSTM.py
                python: CPython 3.12.9
                root: F:\Codes\Wd-Pred
                startedAt: "2025-12-07T13:05:04.043398Z"
                writerId: d7w1u5mprpwp4jfckf47ou0vahbjtwhe
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.12.9
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
batch_size:
    value: 1024
epochs:
    value: 40
focal_gamma:
    value: 2
learning_rate:
    value: 0.0005
look_back:
    value: 5
model_type:
    value: LSTM (Focal + F2 + Full Metrics)
