_wandb:
    value:
        cli_version: 0.23.0
        e:
            v1chjb23ynvx62lqsijnm4w8xkgryyj8:
                codePath: LSTM_prediction.py
                codePathLocal: LSTM_prediction.py
                executable: D:\Python\Python312\python.exe
                git:
                    commit: d64c6db3930d31c12912565942c35d5909a97c58
                    remote: https://github.com/AlanMC123/Wd-Pred.git
                host: KanchoTX5Pro
                os: Windows-11-10.0.26100-SP0
                program: f:\Codes\Wd-Pred\LSTM_prediction.py
                python: CPython 3.12.9
                root: F:\Codes\Wd-Pred
                startedAt: "2025-12-02T02:51:46.199876Z"
                writerId: v1chjb23ynvx62lqsijnm4w8xkgryyj8
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
            "3":
                - 13
                - 16
            "4": 3.12.9
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
batch_size:
    value: 512
dropout_rate:
    value: 0.3
embedding_dim:
    value: 64
epochs:
    value: 30
grid_feat_dim:
    value: 4
l2_reg:
    value: 0.0001
look_back:
    value: 5
max_tries:
    value: 6
rnn_units:
    value: 128
vocab_size:
    value: 12000
