_wandb:
    value:
        cli_version: 0.23.0
        e:
            53hjhz0dyk2o6fde6olwrxhdecobtfsf:
                codePath: transformer_prediction.py
                codePathLocal: transformer_prediction.py
                executable: D:\Python\Python312\python.exe
                git:
                    commit: 9321dfdf18582007f9c6b80a73093e7061561088
                    remote: https://github.com/AlanMC123/Wd-Pred.git
                host: KanchoTX5Pro
                os: Windows-11-10.0.26100-SP0
                program: f:\Codes\Wd-Pred\transformer_prediction.py
                python: CPython 3.12.9
                root: F:\Codes\Wd-Pred
                startedAt: "2025-12-01T07:16:04.356919Z"
                writerId: 53hjhz0dyk2o6fde6olwrxhdecobtfsf
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.9
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
batch_size:
    value: 1024
dropout_rate:
    value: 0.15
embedding_dim:
    value: 32
epochs:
    value: 15
ff_dim:
    value: 108
key_dim:
    value: 36
learning_rate:
    value: 0.0005
look_back:
    value: 8
model_type:
    value: Transformer
num_heads:
    value: 4
seed:
    value: 2025
transformer_layers:
    value: 2
