_wandb:
    value:
        cli_version: 0.23.0
        e:
            l17as55oww7jthanukqiqfqdthpladrn:
                codePath: train_LSTM.py
                codePathLocal: train_LSTM.py
                executable: D:\Python\Python312\python.exe
                git:
                    commit: ba951a10d072f8339f0745f9080c5e5eb9170c47
                    remote: https://github.com/AlanMC123/Wd-Pred.git
                host: KanchoTX5Pro
                os: Windows-11-10.0.26100-SP0
                program: f:\Codes\Wd-Pred\train_LSTM.py
                python: CPython 3.12.9
                root: F:\Codes\Wd-Pred
                startedAt: "2025-12-07T04:21:13.065533Z"
                writerId: l17as55oww7jthanukqiqfqdthpladrn
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.12.9
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
GRID_FEAT_LEN:
    value: 8
batch_size:
    value: 1024
dropout_rate:
    value: 0.45
embedding_dim:
    value: 24
epochs:
    value: 40
learning_rate:
    value: 0.0005
look_back:
    value: 5
lstm_units:
    value: 56
model_type:
    value: LSTM_Grid_Seq_Simplified
seed:
    value: 42
