_wandb:
    value:
        cli_version: 0.23.0
        e:
            q3wc1qnlza7uz2njmfxkdq11oj8h2jgd:
                codePath: LSTM_prediction.py
                codePathLocal: LSTM_prediction.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "749329182720"
                        used: "368686268416"
                executable: D:\Python\Python312\python.exe
                git:
                    commit: e82eb56ee09136435ec77154b20c75b95600c75c
                    remote: https://github.com/AlanMC123/Wd-Pred.git
                gpu: NVIDIA GeForce RTX 4070 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4608
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4070 Laptop GPU
                      uuid: GPU-91ab717b-1e4f-0366-eefd-b8f5234000cc
                host: KanchoTX5Pro
                memory:
                    total: "68319449088"
                os: Windows-11-10.0.26100-SP0
                program: f:\Codes\Wd-Pred\LSTM_prediction.py
                python: CPython 3.12.9
                root: F:\Codes\Wd-Pred
                startedAt: "2025-11-30T16:42:24.060386Z"
                writerId: q3wc1qnlza7uz2njmfxkdq11oj8h2jgd
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
            "3":
                - 3
                - 8
                - 13
                - 16
            "4": 3.12.9
            "5": 0.23.0
            "8":
                - 3
            "10":
                - 17
            "12": 0.23.0
            "13": windows-amd64
batch_size:
    value: 1024
dropout_rate:
    value: 0.15
embedding_dim:
    value: 24
epochs:
    value: 15
learning_rate:
    value: 0.001
look_back:
    value: 8
lstm_units:
    value: 64
model_type:
    value: LSTM
seed:
    value: 42
